
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]



      # docker run --rm    --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v c:/docker/volumes/postgres:/var/lib/postgresql/data  postgres 

      # C:\OneDrive\Projects\project-8-docker-and-postgres\Commands.txt
